@Server_HostAddress = http://localhost:5378

GET {{Server_HostAddress}}/api/king/status
Accept: application/json

###

GET {{Server_HostAddress}}/api/king/spots
Accept: application/json

###

GET {{Server_HostAddress}}/api/king/map
Accept: application/json

###
